---
- name: generate kubeadm join command
  hosts: master1
  become: yes
  gather_facts: no
  tasks:
    - name: Generate kubeadm join commmand
      shell: kubeadm token create --print-join-command --ttl 24h
      register: join_command_output
      changed_when: changed

    - name: Set join command as a fact
      set_fact:
      join_command: "{{ join_command_output.stdout}}"

    - name: set join command as a file
      copy:
      content: "{{ join_command }}"
      dest: /etc/kubernetes/jin_command.txt
      mode: "0644"

    - name: Print Join command
      debug:
        msg: "{{ join_command }}"

    - name: join worker nodes to kubernetes cluster
      become: yes
      gather_facts: no
      command: "{{ hostvars['master1'].join_command}}"
      enviroment:
        KUBECONFIG: /home/ansible-user/.kube/config
      delegate_to: "{ item }"
      with_items: "{{ groups['node']}}"
      register: join_result
      changed_when: true

    - name: Restart the kubelet after joining the cluster_nodes
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
        delegate_to: "{ item }"
        with_items: "{{ groups['node']}}"
