---
- name: Generate join command for adding new master
  hosts: master1
  become: yes
  tasks:
    - name: Generate join command for new masters
      command: kubeadm token create --print-join-command
      register: join_command
      environment:
        KUBECONFIG: /home/ansible-user/.kube/config

- name: Add new masters to the cluster
  hosts: master2,master3
  become: yes
  tasks:
    - name: Check if node is part of the cluster
      command: kubectl get nodes --no-headers -o custom-columns=":metadata.name"
      register: cluster_nodes
      environment:
        KUBECONFIG: /home/ansible-user/.kube/config
      changed_when: false

    - name: Join master node to the cluster
      command: "{{ hostvars['master1']['join_command']['stdout'] }} --control-plane"
      when: inventory_hostname not in cluster_nodes.stdout
      environment:
        KUBECONFIG: /home/ansible-user/.kube/config
