---
- name: Generate kubeadm join command
  hosts: master1
  become: yes
  gather_facts: no
  tasks:
    - name: Generate kubeadm join command
      shell: kubeadm token create --print-join-command --ttl 24h
      register: join_command_output
      changed_when: false  

    - name: Set join command as a fact
      set_fact:
        join_command: "{{ join_command_output.stdout }}"

    - name: Save join command to a file
      copy:
        content: "{{ join_command }}"
        dest: /etc/kubernetes/join_command.txt
        mode: '0644'  # Ensure proper permissions for the file

    - name: Print join command
      debug:
        msg: "{{ join_command }}"

    - name: Join worker nodes to the Kubernetes cluster
      become: yes
      gather_facts: no
      command: "{{ hostvars['master1'].join_command }}"
      environment:
        KUBECONFIG: /etc/kubernetes/kubelet.conf
      delegate_to: "{{ item }}"  
      with_items: "{{ groups['node'] }}"  
      register: join_result
      changed_when: true  

    - name: Restart kubelet after joining the cluster
      systemd:
        name: kubelet
        state: restarted
        enabled: yes  
      delegate_to: "{{ item }}"  
      with_items: "{{ groups['node'] }}" 
