---
- import_playbook: k8s-setup.yaml hostlist=k8s_node
- import_playbook: helm-install.yaml hostlist=k8s_node
- import_playbook: time-sync.yaml hostlist=k8s_node
- import_playbook: kubernetes_role.yaml hostlist=k8s_node
- import_playbook: first-master.yaml hostlist=master1
- import_playbook: copy-admin-conf.yaml hostlist=k8s_node
- import_playbook: kubectl-local.yaml    hostlist=local
- import_playbook: configure_cni.yaml hostlist=k8s_node
- import_playbook: join-masters.yaml hostlist=master2:master3
- import_playbook: label-nodes.yaml hostlist=controlplane
- import_playbook: configure_cni.yaml hostlist=k8s_node
- import_playbook: join-worker.yaml hostlist=node
- import_playbook: nfs.yaml hostlist=nfs-server
- import_playbook: nfs-setup.yaml hostlist=k8s_node
