---
- import_playbook: k8s-setup.yaml hostlist=k8s_node
- import_playbook: time-sync.yaml hostlist=k8s_node
- import_playbook: first-master.yaml hostlist=master1
- import_playbook: join-master.yaml hostlist=master2:master3
- import_playbook: join-worker.yaml hostlist=node
